---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: malston/gradle-java-8
inputs:
  - name: version
  - name: repo
  - name: gradle
outputs:
  - name: build
run:
  path: /bin/bash
  args: ["-c", "repo/ci/tasks/scripts/build-rc.sh"]
params:
  JAVA_OPTIONS:
