---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: malston/gradle-java-8
inputs:
  - name: gradle
  - name: repo
outputs:
  - name: build
run:
  path: /bin/bash
  args: ["-c", "repo/concourse/tasks/scripts/build.sh"]
params:
  JAVA_OPTIONS:
