---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-jdk
inputs:
  - name: pipeline
  - name: version
  - name: repo
  - name: repo-release
  - name: gradle
outputs:
  - name: out
run:
  path: /bin/bash
  args:
    - pipeline/concourse/tasks/scripts/bump-to-release-version.sh
params:
  GIT_EMAIL:
  GIT_NAME:
