---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: getourneau/alpine-bash-git
inputs:
  - name: pipeline
  - name: repo
  - name: repo-release
outputs:
  - name: out
run:
  path: /bin/bash
  args:
  - pipeline/concourse/tasks/scripts/merge-release-branch.sh
params:
  GIT_EMAIL:
  GIT_NAME:
