---
image_resource:
  type: docker-image
  source:
    repository: malston/gradle-java-8
platform: linux
inputs:
  - name: pipeline
  - name: repo
  - name: gradle
run:
  path: /bin/bash
  args: ["-c", "pipeline/concourse/tasks/scripts/sonar.sh"]
params:
  SONAR_URL:
