---
image_resource:
  type: docker-image
  source:
    repository: malston/gradle-java-8
platform: linux
inputs:
  - name: version
  - name: repo
  - name: gradle
run:
  path: /bin/bash
  args: ["-c", "repo/ci/tasks/scripts/upload-archives.sh"]
params:
  NEXUS_URL:
