---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: malston/gradle-java-8
inputs:
  - name: pipeline
  - name: repo
  - name: gradle
run:
  path: /bin/bash
  args: ["-c", "pipeline/concourse/tasks/scripts/unit.sh"]
